import type { CardDefinition } from "./types";

const assetBase = (import.meta as ImportMeta & { env?: { BASE_URL?: string } }).env?.BASE_URL ?? "/";
const raverImage = (id: string) => `${assetBase}assets/cards/raver/art/${id}.png`;
const awarenessImage = (id: string) => `${assetBase}assets/cards/awareness/art/${id}.png`;
const dealerImage = (id: string) => `${assetBase}assets/cards/dealer/art/${id}.png`;
const neutralImage = (id: string) => `${assetBase}assets/cards/neutral/art/${id}.png`;

export const cards: CardDefinition[] = [
  // Raver
  {
    id: "raver_auf_anschlag",
    name: "Puls im roten Bereich",
    kind: "person",
    faction: "raver",
    tags: ["stimulans", "rausch"],
    cost: 1,
    image: raverImage("raver_auf_anschlag"),
    attack: 2,
    stability: 1,
    effect: "Beim Ausspielen: Wenn du bereits Rausch hast, erhaelt diese Person +1 Angriff.",
    drawback: "+1 Rausch.",
    flavor: "Tempo ist keine Richtung.",
  },
  {
    id: "raver_anreissen",
    name: "Lichtkegel-Mut",
    kind: "aktion",
    faction: "raver",
    tags: ["rausch"],
    cost: 1,
    image: raverImage("raver_anreissen"),
    effect: "Eine eigene Person erhaelt +2 Angriff.",
    drawback: "+1 Rausch.",
    flavor: "Kurz sieht alles machbar aus.",
  },
  {
    id: "raver_clubgaenger",
    name: "Frontrow-Taenzer",
    kind: "person",
    faction: "raver",
    tags: ["stimulans", "rausch"],
    cost: 2,
    image: raverImage("raver_clubgaenger"),
    attack: 2,
    stability: 2,
    effect: "Beim Ausspielen: Wenn dein Rausch 3+ ist, erhaelt diese Person +1 Angriff.",
    flavor: "Immer da, wo es am lautesten ist.",
  },
  {
    id: "raver_druckwelle",
    name: "Bassdruck",
    kind: "aktion",
    faction: "raver",
    tags: ["rausch"],
    cost: 2,
    image: raverImage("raver_druckwelle"),
    effect: "Eine gegnerische Person verliert 2 Angriff.",
    drawback: "+1 Rausch.",
    flavor: "Der Raum trifft zurueck.",
  },
  {
    id: "raver_nachlegen",
    name: "Noch eine Runde",
    kind: "person",
    faction: "raver",
    tags: ["stimulans", "rausch"],
    cost: 3,
    image: raverImage("raver_nachlegen"),
    attack: 3,
    stability: 2,
    effect: "Kann sofort angreifen, wenn du 2+ Rausch hast.",
    drawback: "Wenn diese Person angreift: +1 Rausch.",
    flavor: "Der gefaehrlichste Satz am Morgen.",
  },
  {
    id: "raver_kieferkrampf",
    name: "Zitternder Fokus",
    kind: "aktion",
    faction: "raver",
    tags: ["rausch"],
    cost: 3,
    image: raverImage("raver_kieferkrampf"),
    effect: "Eine eigene Person erhaelt +1/+1. Ziehe 1 Karte.",
    drawback: "+1 Rausch.",
    flavor: "Der Koerper schreibt mit.",
  },
  {
    id: "raver_filmriss",
    name: "Schwarzes Loch",
    kind: "person",
    faction: "raver",
    tags: ["rausch"],
    cost: 4,
    image: raverImage("raver_filmriss"),
    attack: 4,
    stability: 3,
    effect: "Starke Person mit hohem Risiko.",
    drawback: "Bei Rausch 5+ verliert sie am Ende deines Zuges 1 Gesundheit.",
    flavor: "Die Luecke gewinnt immer.",
  },
  {
    id: "raver_kein_morgen",
    name: "Kein Morgen danach",
    kind: "aktion",
    faction: "raver",
    tags: ["rausch"],
    cost: 5,
    image: raverImage("raver_kein_morgen"),
    effect: "Fuege dem Gegner 4 Schaden zu. Bei Rausch 5+: 6 Schaden.",
    drawback: "Verliere 2 Stabilitaet.",
    flavor: "Ein Finale ohne Abspann.",
  },
  {
    id: "raver_bassdruck",
    name: "Boxenturm",
    kind: "aktion",
    faction: "raver",
    tags: ["rausch"],
    cost: 2,
    image: raverImage("raver_bassdruck"),
    effect: "Fuege einer gegnerischen Person 2 Schaden zu. Bei Rausch 3+: 3 Schaden.",
    drawback: "+1 Rausch.",
    flavor: "Mehr Vibration als Argument.",
  },
  {
    id: "raver_durchballern",
    name: "Tunnelblick",
    kind: "aktion",
    faction: "raver",
    tags: ["rausch"],
    cost: 4,
    image: raverImage("raver_durchballern"),
    effect: "Alle eigenen Personen erhalten +1 Angriff. Eine eigene Person kann sofort angreifen.",
    drawback: "+2 Rausch. Verliere 1 Stabilitaet.",
    flavor: "Alles nach vorn, nichts nachdenken.",
  },
  {
    id: "raver_ueberdreht",
    name: "Neon-Nerven",
    kind: "person",
    faction: "raver",
    tags: ["rausch"],
    cost: 4,
    image: raverImage("raver_ueberdreht"),
    attack: 3,
    stability: 4,
    effect: "Am Ende deines Zuges erhalten andere eigene Personen +1 Angriff.",
    drawback: "Bei Rausch 5+ erhaeltst du stattdessen +1 Rausch.",
    flavor: "Das Zittern nennt sich kurz Energie.",
  },
  {
    id: "raver_zusammenbruch",
    name: "Abrisskante",
    kind: "aktion",
    faction: "raver",
    tags: ["rausch"],
    cost: 6,
    image: raverImage("raver_zusammenbruch"),
    effect: "Fuege allen gegnerischen Personen 1 Schaden zu. Setze deinen Rausch auf 0.",
    drawback: "Verliere bis zu 4 Stabilitaet fuer entfernten Rausch.",
    flavor: "Irgendwann endet der Track.",
  },
  {
    id: "hero_raver_spotlight",
    name: "Spotlight-Sprinter",
    kind: "person",
    faction: "raver",
    tags: ["rausch"],
    cost: 0,
    image: raverImage("raver_auf_anschlag"),
    attack: 2,
    stability: 1,
    effect: "Temporaere Heldenskill-Person. Kann sofort angreifen und verschwindet am Ende deines Zuges.",
    drawback: "Nur durch den Heldenskill beschworen.",
    flavor: "Ein kurzer Auftritt, dann ist die Buehne leer.",
  },

  // Awareness
  {
    id: "awareness_wasser",
    name: "Wasser reichen",
    kind: "aktion",
    faction: "awareness",
    tags: ["harm-reduction"],
    cost: 1,
    image: awarenessImage("awareness_wasser"),
    effect: "Waehle dich oder eine eigene Person. Held: +2 Stabilitaet. Person: +2 HP. Reduziere Rausch um 1.",
    flavor: "Keine Pose, nur Hilfe.",
  },
  {
    id: "awareness_aufsicht",
    name: "Ruhiger Blick",
    kind: "person",
    faction: "awareness",
    tags: ["harm-reduction"],
    cost: 1,
    image: awarenessImage("awareness_aufsicht"),
    attack: 1,
    stability: 3,
    effect: "Am Ende deines Zuges heile 1 Stabilitaet, falls deine Stabilitaet 5 oder niedriger ist.",
    flavor: "Jemand bleibt ansprechbar.",
  },
  {
    id: "awareness_substanztest",
    name: "Teststreifen",
    kind: "aktion",
    faction: "awareness",
    tags: ["harm-reduction"],
    cost: 2,
    image: awarenessImage("awareness_substanztest"),
    effect: "Reduziere Rausch oder Abhaengigkeit um 2. Ziehe 1 Karte.",
    flavor: "Wissen ersetzt keine Vorsicht, aber es hilft.",
  },
  {
    id: "awareness_krisenhelferin",
    name: "Sanfter Griff",
    kind: "person",
    faction: "awareness",
    tags: ["harm-reduction"],
    cost: 2,
    image: awarenessImage("awareness_krisenhelferin"),
    attack: 1,
    stability: 4,
    effect: "Wenn eine eigene Person Schaden erhaelt: Heile 1 Stabilitaet. Maximal einmal pro Zug.",
    flavor: "Nicht festhalten. Stabilisieren.",
  },
  {
    id: "awareness_schadensbegrenzung",
    name: "Situation beruhigen",
    kind: "aktion",
    faction: "awareness",
    tags: ["harm-reduction"],
    cost: 2,
    image: awarenessImage("awareness_schadensbegrenzung"),
    effect: "Eine gegnerische Person verliert Angriffsbuffs. Reduziere deine Fahndung um 1.",
    flavor: "Weniger Schaden ist manchmal der Sieg.",
  },
  {
    id: "awareness_streetworker",
    name: "Nachtkontakt",
    kind: "person",
    faction: "awareness",
    tags: ["harm-reduction"],
    cost: 3,
    image: awarenessImage("awareness_streetworker"),
    attack: 2,
    stability: 4,
    effect: "Am Ende deines Zuges reduziere deinen hoechsten Risikowert um 1.",
    flavor: "Fragt nicht, um zu richten.",
  },
  {
    id: "awareness_deeskalation",
    name: "Ruhige Ansage",
    kind: "aktion",
    faction: "awareness",
    tags: ["harm-reduction"],
    cost: 3,
    image: awarenessImage("awareness_deeskalation"),
    effect: "Eine gegnerische Person erhaelt -2 Angriff. Reduziere Fahndung beider Spieler um 1.",
    flavor: "Leiser kann staerker sein.",
  },
  {
    id: "awareness_therapieplatz",
    name: "Beratungsstelle",
    kind: "ort",
    faction: "awareness",
    tags: ["harm-reduction", "abhaengigkeit"],
    cost: 4,
    image: awarenessImage("awareness_therapieplatz"),
    effect: "Heile 2 Stabilitaet. Wenn du schon volle Stabilitaet hast: Reduziere Abhaengigkeit um 1.",
    flavor: "Langsam ist hier kein Nachteil.",
  },
  {
    id: "awareness_rueckzugsraum",
    name: "Chillout-Raum",
    kind: "ort",
    faction: "awareness",
    tags: ["harm-reduction"],
    cost: 2,
    image: awarenessImage("awareness_rueckzugsraum"),
    effect: "Reduziere deinen Rausch um 1.",
    flavor: "Eine Tuer, ein Stuhl, weniger Druck.",
  },
  {
    id: "awareness_abschirmen",
    name: "Schutzkreis",
    kind: "aktion",
    faction: "awareness",
    tags: ["harm-reduction"],
    cost: 3,
    image: awarenessImage("awareness_abschirmen"),
    effect: "Alle eigenen Personen erhalten +2 Gesundheit. Heile 2 Stabilitaet.",
    flavor: "Grenzen retten Tempo fuer spaeter.",
  },
  {
    id: "awareness_intervention",
    name: "Klare Grenze",
    kind: "aktion",
    faction: "awareness",
    tags: ["harm-reduction"],
    cost: 4,
    image: awarenessImage("awareness_intervention"),
    effect: "Eine gegnerische Person verliert Buffs und kann im naechsten Zug nicht angreifen.",
    flavor: "Nicht hart. Deutlich.",
  },
  {
    id: "awareness_klarer_kopf",
    name: "Klarer Kopf",
    kind: "aktion",
    faction: "awareness",
    tags: ["harm-reduction", "abhaengigkeit"],
    cost: 6,
    image: awarenessImage("awareness_klarer_kopf"),
    effect: "Setze deinen Rausch auf 0. Reduziere Abhaengigkeit um 2. Heile 4 Stabilitaet.",
    flavor: "Nicht spektakulaer. Genau richtig.",
  },

  // Dealer
  {
    id: "dealer_laeufer",
    name: "Hintertuer-Laeufer",
    kind: "person",
    faction: "dealer",
    tags: ["deal", "fahndung"],
    cost: 1,
    image: dealerImage("dealer_laeufer"),
    attack: 1,
    stability: 2,
    effect: "Beim Ausspielen erhaeltst du +1 Cash in diesem Zug.",
    drawback: "+1 Cash ist nur in diesem Zug verfuegbar.",
    flavor: "Je schneller der Weg, desto sichtbarer die Spur.",
  },
  {
    id: "dealer_kleiner_lauf",
    name: "Schneller Umschlag",
    kind: "aktion",
    faction: "dealer",
    tags: ["deal", "fahndung"],
    cost: 1,
    image: dealerImage("dealer_kleiner_lauf"),
    effect: "Erhalte +2 Cash in diesem Zug.",
    drawback: "+1 Fahndung.",
    flavor: "Kleiner Vorteil, grosse Spur.",
  },
  {
    id: "dealer_stammkunde",
    name: "Bekanntes Gesicht",
    kind: "person",
    faction: "dealer",
    tags: ["deal"],
    cost: 2,
    image: dealerImage("dealer_stammkunde"),
    attack: 2,
    stability: 3,
    effect: "Beim Ausspielen: Wenn du danach noch Cash hast, erhaelt diese Person +1 Angriff.",
    flavor: "Vertraut wirkt nur kurz sicher.",
  },
  {
    id: "dealer_schnelles_geld",
    name: "Bargelddruck",
    kind: "aktion",
    faction: "dealer",
    tags: ["deal", "fahndung"],
    cost: 2,
    image: dealerImage("dealer_schnelles_geld"),
    effect: "Ziehe 1 Karte. Erhalte +1 Cash in diesem Zug.",
    drawback: "+1 Fahndung.",
    flavor: "Papier raschelt lauter als gedacht.",
  },
  {
    id: "dealer_bunkern",
    name: "Spuren verwischen",
    kind: "aktion",
    faction: "dealer",
    tags: ["deal", "fahndung"],
    cost: 2,
    image: dealerImage("dealer_bunkern"),
    effect: "Reduziere deine Fahndung um 1. Erhalte +1 Cash in diesem Zug.",
    flavor: "Ordnung ist hier nur Tarnung.",
  },
  {
    id: "dealer_druckmittel",
    name: "Schiefer Deal",
    kind: "aktion",
    faction: "dealer",
    tags: ["deal", "fahndung"],
    cost: 3,
    image: dealerImage("dealer_druckmittel"),
    effect: "Fuege einer gegnerischen Person 3 Schaden zu. Wenn du danach noch Cash hast: 5 Schaden.",
    drawback: "+1 Fahndung.",
    flavor: "Ein Angebot, das schon droht.",
  },
  {
    id: "dealer_mittelsmann",
    name: "Kontakt im Flur",
    kind: "person",
    faction: "dealer",
    tags: ["deal", "fahndung"],
    cost: 3,
    image: dealerImage("dealer_mittelsmann"),
    attack: 3,
    stability: 3,
    effect: "Beim Ausspielen erhaeltst du +1 Cash in diesem Zug.",
    drawback: "+1 Fahndung.",
    flavor: "Er kennt jemanden. Leider kennen ihn auch andere.",
  },
  {
    id: "dealer_abziehen",
    name: "Kasse leeren",
    kind: "aktion",
    faction: "dealer",
    tags: ["deal", "fahndung"],
    cost: 5,
    image: dealerImage("dealer_abziehen"),
    effect: "Nach dem Bezahlen: Gib dein restliches Cash aus. Fuege dem Gegner so viel Schaden zu, maximal 6.",
    drawback: "+2 Fahndung. Bei Fahndung 6+: -2 Stabilitaet.",
    flavor: "Alles raus. Alles sichtbar.",
  },
  {
    id: "dealer_schuldenbuch",
    name: "Offenes Schuldenbuch",
    kind: "ort",
    faction: "dealer",
    tags: ["deal"],
    cost: 2,
    image: dealerImage("dealer_schuldenbuch"),
    effect: "Beim Ausspielen: +1 Cash und 1 Schaden am Gegner.",
    drawback: "Bei Fahndung 5+: -1 Gesundheit.",
    flavor: "Nichts verschwindet. Es wartet nur.",
  },
  {
    id: "dealer_falscher_freund",
    name: "Falscher Freund",
    kind: "person",
    faction: "dealer",
    tags: ["deal"],
    cost: 3,
    image: dealerImage("dealer_falscher_freund"),
    attack: 2,
    stability: 5,
    effect: "Beim Ausspielen erhaeltst du +1 Cash in diesem Zug.",
    drawback: "Bei Fahndung 6+: Diese Person verliert 2 Gesundheit.",
    flavor: "Zu nah, um billig zu bleiben.",
  },
  {
    id: "dealer_grosse_lieferung",
    name: "Dicke Lieferung",
    kind: "aktion",
    faction: "dealer",
    tags: ["deal", "fahndung"],
    cost: 4,
    image: dealerImage("dealer_grosse_lieferung"),
    effect: "Erhalte +4 Cash in diesem Zug. Ziehe 1 Karte.",
    drawback: "+3 Fahndung.",
    flavor: "Zu gross, um leise zu bleiben.",
  },
  {
    id: "dealer_netzwerk",
    name: "Telefonkette",
    kind: "ort",
    faction: "dealer",
    tags: ["deal", "fahndung"],
    cost: 6,
    image: dealerImage("dealer_netzwerk"),
    effect: "Erhalte +2 Cash in diesem Zug. Deine Dealer-Personen erhalten +1 Angriff.",
    drawback: "+1 Fahndung.",
    flavor: "Alle kennen jemanden. Irgendwann kennt jeder dich.",
  },

  // Neutral
  {
    id: "neutral_verpeilter_gast",
    name: "Verpeilter Gast",
    kind: "person",
    faction: "neutral",
    tags: ["neutral"],
    cost: 1,
    image: neutralImage("neutral_verpeilter_gast"),
    attack: 1,
    stability: 2,
    effect: "Einfache Person ohne Soforteffekt.",
    flavor: "Niemand weiss, wer ihn eingeladen hat.",
  },
  {
    id: "neutral_wasserflasche",
    name: "Wasserflasche",
    kind: "aktion",
    faction: "neutral",
    tags: ["harm-reduction", "neutral"],
    cost: 1,
    image: neutralImage("neutral_wasserflasche"),
    effect: "Waehle dich oder eine eigene Person. Held: +1 Stabilitaet. Person: +1 HP. Reduziere Rausch um 1.",
    flavor: "Das kleinste gute Zeichen.",
  },
  {
    id: "neutral_kontaktperson",
    name: "Kontaktperson",
    kind: "person",
    faction: "neutral",
    tags: ["neutral"],
    cost: 2,
    image: neutralImage("neutral_kontaktperson"),
    attack: 2,
    stability: 2,
    effect: "Wenn du keine andere Person kontrollierst, ziehe 1 Karte.",
    flavor: "Kennt den Weg raus. Vielleicht.",
  },
  {
    id: "neutral_schlechter_einfluss",
    name: "Schlechter Einfluss",
    kind: "person",
    faction: "neutral",
    tags: ["rausch", "neutral"],
    cost: 2,
    image: neutralImage("neutral_schlechter_einfluss"),
    attack: 2,
    stability: 2,
    effect: "Eine andere eigene Person erhaelt +1 Angriff.",
    drawback: "+1 Rausch.",
    flavor: "Manchmal ist Druck ein Laecheln.",
  },
  {
    id: "neutral_erste_hilfe",
    name: "Erste Hilfe",
    kind: "aktion",
    faction: "neutral",
    tags: ["harm-reduction", "neutral"],
    cost: 2,
    image: neutralImage("neutral_erste_hilfe"),
    effect: "Waehle dich oder eine eigene Person. Held: +4 Gesundheit. Person: +4 HP.",
    flavor: "Nicht elegant. Wirksam.",
  },
  {
    id: "neutral_panikmoment",
    name: "Panikmoment",
    kind: "aktion",
    faction: "neutral",
    tags: ["neutral"],
    cost: 2,
    image: neutralImage("neutral_panikmoment"),
    effect: "Fuege der ersten gegnerischen Person 2 Schaden zu. Wenn es keine gibt, trifft es deine erste Person. Beide Spieler verlieren 1 Stabilitaet.",
    flavor: "Alle merken es gleichzeitig.",
  },
  {
    id: "neutral_taxi_nach_hause",
    name: "Taxi nach Hause",
    kind: "aktion",
    faction: "neutral",
    tags: ["harm-reduction", "neutral"],
    cost: 2,
    image: neutralImage("neutral_taxi_nach_hause"),
    effect: "Entferne eine eigene Person vom Board. Heile 3 Stabilitaet. Reduziere Rausch um 1.",
    flavor: "Der unspektakulaere Sieg.",
  },
  {
    id: "neutral_gruppendruck",
    name: "Gruppendruck",
    kind: "aktion",
    faction: "neutral",
    tags: ["rausch", "neutral"],
    cost: 3,
    image: neutralImage("neutral_gruppendruck"),
    effect: "Alle Personen erhalten +1 Angriff.",
    drawback: "Beide Spieler erhalten +1 Rausch.",
    flavor: "Wenn keiner nein sagt.",
  },
  {
    id: "neutral_razzia_geruecht",
    name: "Razzia-Geruecht",
    kind: "aktion",
    faction: "neutral",
    tags: ["polizei", "fahndung", "neutral"],
    cost: 3,
    image: neutralImage("neutral_razzia_geruecht"),
    effect: "Beide Spieler erhalten +1 Fahndung. Ziehe 1 Karte.",
    flavor: "Vielleicht stimmt es. Reicht schon.",
  },
  {
    id: "neutral_ruhiger_rueckzugsort",
    name: "Ruhiger Rueckzugsort",
    kind: "ort",
    faction: "neutral",
    tags: ["harm-reduction", "neutral"],
    cost: 3,
    image: neutralImage("neutral_ruhiger_rueckzugsort"),
    effect: "Heile 1 Stabilitaet.",
    flavor: "Ein Raum ohne Fragen.",
  },
  {
    id: "neutral_ueberforderung",
    name: "Ueberforderung",
    kind: "aktion",
    faction: "neutral",
    tags: ["neutral"],
    cost: 3,
    image: neutralImage("neutral_ueberforderung"),
    effect: "Eine Person erhaelt -2 Angriff. Ihr Besitzer verliert 1 Stabilitaet.",
    flavor: "Zu viel, zu laut, zu nah.",
  },
  {
    id: "neutral_razzia",
    name: "Razzia",
    kind: "aktion",
    faction: "neutral",
    tags: ["polizei", "fahndung", "neutral"],
    cost: 5,
    image: neutralImage("neutral_razzia"),
    effect: "Fuege allen Personen mit Fahndungs- oder Deal-Tag 3 Schaden zu.",
    drawback: "Setze die Fahndung beider Spieler auf mindestens 4.",
    flavor: "Wenn Risiko ploetzlich Uniform traegt.",
  },
  {
    id: "neutral_frische_luft",
    name: "Frische Luft",
    kind: "aktion",
    faction: "neutral",
    tags: ["harm-reduction", "neutral"],
    cost: 1,
    image: neutralImage("neutral_frische_luft"),
    effect: "Reduziere Rausch um 1. Wenn du vorher Rausch 3+ hattest, heile 1 Stabilitaet.",
    flavor: "Draussen ist nicht alles gut. Aber anders.",
  },
  {
    id: "neutral_leerer_akku",
    name: "Leerer Akku",
    kind: "aktion",
    faction: "neutral",
    tags: ["neutral"],
    cost: 2,
    image: neutralImage("neutral_leerer_akku"),
    effect: "Ziehe 1 Karte.",
    flavor: "Niemand erreicht irgendwen.",
  },
  {
    id: "neutral_kaputter_schlaf",
    name: "Kaputter Schlaf",
    kind: "aktion",
    faction: "neutral",
    tags: ["neutral"],
    cost: 4,
    image: neutralImage("neutral_kaputter_schlaf"),
    effect: "Heile 4 Gesundheit.",
    drawback: "Verliere 2 Stabilitaet.",
    flavor: "Der Koerper liegt. Der Kopf nicht.",
  },
  {
    id: "neutral_offene_rechnung",
    name: "Offene Rechnung",
    kind: "ort",
    faction: "neutral",
    tags: ["neutral"],
    cost: 4,
    image: neutralImage("neutral_offene_rechnung"),
    effect: "Fuege dem Gegner 2 Schaden zu. Verliere 1 Cash in diesem Zug.",
    drawback: "Wenn du kein Cash verlieren kannst: -2 Stabilitaet.",
    flavor: "Irgendwann zahlt jemand.",
  },
  {
    id: "neutral_morgen_danach",
    name: "Morgen Danach",
    kind: "aktion",
    faction: "neutral",
    tags: ["harm-reduction", "neutral"],
    cost: 5,
    image: neutralImage("neutral_morgen_danach"),
    effect: "Entferne Angriffsbuffs von allen Personen. Setze den Rausch beider Spieler auf 0.",
    drawback: "Beide Spieler verlieren 2 Stabilitaet.",
    flavor: "Das Licht ist unfreundlich ehrlich.",
  },
  {
    id: "neutral_szenekenner",
    name: "Szenekenner",
    kind: "person",
    faction: "neutral",
    tags: ["neutral"],
    cost: 3,
    image: neutralImage("neutral_szenekenner"),
    attack: 2,
    stability: 4,
    effect: "Solide neutrale Person ohne Soforteffekt.",
    flavor: "Hat alles schon gesehen. Sagt er.",
  },
  {
    id: "neutral_afterhour_sog",
    name: "Afterhour-Sog",
    kind: "aktion",
    faction: "neutral",
    tags: ["rausch", "neutral"],
    cost: 3,
    image: neutralImage("neutral_gruppendruck"),
    effect: "Ziehe 2 Karten.",
    drawback: "+2 Rausch.",
    flavor: "Noch eine Stunde wird schnell ein System.",
  },
  {
    id: "neutral_craving_schub",
    name: "Craving-Schub",
    kind: "aktion",
    faction: "neutral",
    tags: ["abhaengigkeit", "neutral"],
    cost: 2,
    image: neutralImage("neutral_schlechter_einfluss"),
    effect: "Ziehe 2 Karten.",
    drawback: "+1 Abhaengigkeit.",
    flavor: "Der Vorteil fuehlt sich wie ein Bedarf an.",
  },
  {
    id: "neutral_hinterhof_deal",
    name: "Hinterhof-Deal",
    kind: "aktion",
    faction: "neutral",
    tags: ["deal", "fahndung", "neutral"],
    cost: 1,
    image: neutralImage("neutral_kontaktperson"),
    effect: "Erhalte +2 Cash in diesem Zug.",
    drawback: "+1 Fahndung.",
    flavor: "Schnell geloest, schlecht versteckt.",
  },
  {
    id: "neutral_blaulicht_geruecht",
    name: "Blaulicht-Geruecht",
    kind: "aktion",
    faction: "neutral",
    tags: ["polizei", "fahndung", "neutral"],
    cost: 2,
    image: neutralImage("neutral_razzia_geruecht"),
    effect: "Beide Spieler erhalten +1 Fahndung. Ziehe 1 Karte.",
    flavor: "Ob wahr oder nicht: Alle bewegen sich anders.",
  },
  {
    id: "neutral_schlafdefizit",
    name: "Schlafdefizit",
    kind: "aktion",
    faction: "neutral",
    tags: ["rausch", "abhaengigkeit", "neutral"],
    cost: 2,
    image: neutralImage("neutral_kaputter_schlaf"),
    effect: "Fuege einer beliebigen Person 1 Schaden zu. Ziehe 1 Karte.",
    drawback: "+1 Rausch oder, wenn du Rausch 4+ hast, +1 Abhaengigkeit.",
    flavor: "Irgendwann wird Muede sein zu einer Mechanik.",
  },
  {
    id: "neutral_kontrollverlust",
    name: "Kontrollverlust",
    kind: "aktion",
    faction: "neutral",
    tags: ["rausch", "neutral"],
    cost: 4,
    image: neutralImage("neutral_panikmoment"),
    effect: "Fuege allen Personen 1 Schaden zu.",
    drawback: "Beide Spieler erhalten +1 Rausch.",
    flavor: "Der Raum entscheidet fuer alle.",
  },
  {
    id: "neutral_beratungsflyer",
    name: "Beratungsflyer",
    kind: "aktion",
    faction: "neutral",
    tags: ["harm-reduction", "neutral"],
    cost: 1,
    image: neutralImage("neutral_wasserflasche"),
    effect: "Reduziere einen deiner Risikowerte um 1. Ziehe 1 Karte.",
    flavor: "Manchmal reicht ein kleiner Anstoss.",
  },
  {
    id: "neutral_druck_von_aussen",
    name: "Druck von aussen",
    kind: "aktion",
    faction: "neutral",
    tags: ["fahndung", "abhaengigkeit", "neutral"],
    cost: 3,
    image: neutralImage("neutral_ueberforderung"),
    effect: "Eine gegnerische Person erhaelt -1 Angriff. Der Gegner erhaelt +1 Fahndung.",
    drawback: "Du erhaeltst +1 Abhaengigkeit.",
    flavor: "Wer Druck ausuebt, nimmt oft welchen mit.",
  },

  // Generated status cards.
  {
    id: "craving",
    name: "Craving",
    kind: "zustand",
    faction: "neutral",
    tags: ["abhaengigkeit"],
    cost: 0,
    effect: "Wenn gezogen: -2 Stabilitaet oder +1 Abhaengigkeit.",
    flavor: "Keine Aktion. Ein Zwang.",
  },
  {
    id: "entzug",
    name: "Entzug",
    kind: "zustand",
    faction: "neutral",
    tags: ["abhaengigkeit"],
    cost: 0,
    effect: "Zu Beginn deines Zuges: -1 Gesundheit und -1 Stabilitaet.",
    flavor: "Der Koerper erinnert sich an alles.",
  },
];

export const cardById = new Map(cards.map((card) => [card.id, card]));
